import Navbar from '../components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { Toaster } from 'react-hot-toast';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto p-4">
          <Navbar />
          <div className="mt-8">{children}</div>
          <Toaster position="top-center" />
        </div>
      </body>
    </html>
  );
}
